GLOBAL_PASS: maomao1986
ENABLE_LOCAL_YUM_REPOS: false

VIRTUALIP: 10.62.10.65
VIRTUALIP_FQDN: vip.kong62.com

VM_INTERFACE: "ens34"

ENABLE_BOND: false
BOND_INTERFACES: ["ens35", "ens36"]
BOND_NETWORK: "10.62.11.0/24"
BOND_MODE: 6


ENABLE_CEPH: false
CEPH_VERSION: luminous
CEPH_PUBLIC_NETWORK: "10.62.11.0/24"
CEPH_CLUSTER_NETWORK: "10.62.11.0/24"
CEPH_MGR_PORT: 7000
CEPH_OPENSTACK_POOLS: ["vms", "images", "volumes", "backups"]


ENABLE_OPENSTACK: false
OPENSTACK_VERSION: rocky
REGION_NAME: RegionOne
ENABLE_OPENSTACK_BUGS_FIX: true


ENABLE_MYSQL: false
MYSQL_PORT: 3306
GALERA_MONITOR_PORT: 9222
DBREPL_USER: kong62
DBREPL_PASS: password


ENABLE_MEMCACHED: false
MEMCACHED_PORT: 11211
HTTPD_PORT: 80


ENABLE_PACEMAKER: true
PCS_USER: hacluster
PCS_PASS: password
HAPROXY_ADMIN_PORT: 8080
HAPROXY_ADMIN_USER: admin
HAPROXY_ADMIN_PASS: passoword


ENABLE_RABBITMQ: false
RABBITMQ_PORT: 5672
RABBITMQ_MANAGEMENT_PORT: 15672
RABBIT_USER: openstack 
RABBIT_PASS: password


ENABLE_KEYSTONE: false
KEYSTONE_PORT: 5000
KEYSTONE_ADMIN_PORT: 35357
KEYSTONE_DBNAME: keystone
KEYSTONE_DBUSER: keystone
KEYSTONE_DBPASS: password
KEYSTONE_USER: keystone
KEYSTONE_PASS: password


ENABLE_GLANCE: false
GLANCE_API_PORT: 9292
GLANCE_REGISTRY_PORT: 9191
GLANCE_DBNAME: glance
GLANCE_DBUSER: glance
GLANCE_DBPASS: password
GLANCE_USER: glance
GLANCE_PASS: password


ENABLE_NOVA: false
NOVA_API_PORT: 8774
NOVA_METADATA_PORT: 8775
PLACEMENT_API_PORT: 8778
VNCPROXY_PORT: 6080
NOVA_API_DBNAME: nova_api
NOVA_PLACEMENT_DBNAME: placement
NOVA_DBNAME: nova
NOVA_DBUSER: nova
NOVA_DBPASS: password
PLACEMENT_DBUSER: placement
PLACEMENT_DBPASS: password
NOVA_USER: nova
NOVA_PASS: password
PLACEMENT_USER: placement
PLACEMENT_PASS: password


ENABLE_CINDER: false
CINDER_API_PORT: 8776
CINDER_DBNAME: cinder
CINDER_DBUSER: cinder
CINDER_DBPASS: password
CINDER_USER: cinder
CINDER_PASS: password


ENABLE_NEUTRON: false
NEUTRON_API_PORT: 9696
NEUTRON_DBNAME: neutron
NEUTRON_DBUSER: neutron
NEUTRON_DBPASS: password
NEUTRON_USER: neutron
NEUTRON_PASS: password
# MECHANISM_DRIVERS can be set one of openvswitch, linuxbridge
MECHANISM_DRIVERS: openvswitch
ENABLE_LBAAS: true
ENABLE_FWAAS: true


ENABLE_HORIZON: false


ENABLE_INFLUXDATA: false
INFLUXDB_API_PORT: 8086
INFLUXDB_RPC_PORT: 8088
CHRONOGRAF_PORT: 8888
KAPACITOR_PORT: 9092
INFLUXDB_DBNAME: kong62
INFLUXDB_POLICYNAME: kong62


ENABLE_ZABBIX: false
ZABBIX_VERSION: 4.0
ZABBIX_SERVER_PORT: 10051
ZABBIX_AGENT_PORT: 10050
ZABBIX_DBNAME: zabbix
ZABBIX_DBUSER: zabbix
ZABBIX_DBPASS: password


ENABLE_GRAFANA: false
GRAFANA_PORT: 3000


ENABLE_PROMETHEUS: false
PROMETHEUS_VERSION: 2.6.0
PROMETHEUS_PORT: 9090


ENABLE_ELKSTACK: false
ELASTICSEARCH_VERSION: "6.x"
ELASTICSEARCH_PORT: 9200
ELASTICSEARCH_TRANSPORT_PORT: 9300
HEAD_PORT: 9100
KIBANA_PORT: 5601
