- name: Provide logstash.yml to /etc/logstash/logstash.yml
  template: src=logstash.yml.j2 dest=/etc/logstash/logstash.yml
  notify:
    - Restart logstash

- name: Start and Enable logstash
  service: name=logstash state=started enabled=yes
