- name: Create DATABASE CINDER_DBNAME
  mysql_db: name={{CINDER_DBNAME}} state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock
  run_once: yes
  delegate_to: "{{groups['cloud-database'][0]}}"

- name: GRANT ALL PRIVILEGES for CINDER_DBUSER on DATABASE CINDER_DBNAME
  mysql_user: name={{CINDER_DBUSER}} password={% if GLOBAL_PASS %}{{GLOBAL_PASS}}{% else %}{{CINDER_DBPASS}}{% endif %} priv={{CINDER_DBNAME}}.*:ALL host={{item}} state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock
  loop:
    - 'localhost'
    - '%'
  run_once: yes
  delegate_to: "{{groups['cloud-database'][0]}}"
