---
scenario:
  name: fedora-28
platforms:
  - name: fedora-28
    groups:
      - cloud-consul
    image: dokken/fedora-28
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
