---
- name: Prepare
  hosts: all
  tasks:
  - name: Gather variables for each operating system
    debug:
      var: ansible_distribution_release
  - name: Install mysqld server
    package:
      name: "{{ mysql_package }}"
      state: present
  - name: Start mysql server
    systemd:
      name: "{{ mysql_service }}"
      enabled: true
      state: started
  vars:
    mysql_service_map:
      CentOS:
        Core: "mariadb"
      Debian:
        stretch: "mysqld"
      Fedora:
        Twenty Eight: "mariadb"
      Ubuntu:
    mysql_package: "mariadb-server"
    mysql_service: "{{ mysql_service_map[ansible_distribution][ansible_distribution_release] | default('mysql') }}"
