---
- name: Init Centos OS Bases
  hosts: "cloud-memcache"
  gather_facts: true
  vars:
    - test: [ "nihao", "heihei", "kaka", "good"]
  roles:
    - { role: memcached-exporter, when: MEMCACHED_EXPORTER_ENABLED }
  tasks:
    - debug: var=test
      when: test is defined and test
