- name: Start and Enable libvirtd
  service: name=libvirtd state=started enabled=yes
 
- name: Provide secret.xml to /tmp/secret.xml
  template: src=secret.xml.j2 dest=/tmp/secret.xml

- name: Define Secret
  shell: virsh secret-define --file /tmp/secret.xml

- name: Encryption Secret
  shell: virsh secret-set-value --secret f2112853-f8bf-492a-8ef9-744ca49f52ba --base64 $(cat /tmp/client.cinder.key)
