redis_exporter_log_path: "/var/log/redis_exporter.log"
redis_exporter_args: "-redis.addr redis://localhost:{{ REDIS_PORT }} -web.listen-address 0.0.0.0:{{REDIS_EXPORTER_PORT}} -web.telemetry-path /metrics {% if REDIS_PASSWORD %} -redis.password={{REDIS_PASSWORD}} {% endif %}" 
