---
scenario:
  name: centos-7
platforms:
  - name: centos-7
    groups:
      - cloud-consul
    image: dokken/centos-7
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
