---
scenario:
  name: fedora-27
platforms:
  - name: fedora-27
    groups:
      - cloud-consul
    image: dokken/fedora-27
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
