---
# File: site.yml - Example Consul site playbook

- name: Assemble Consul cluster
  hosts: cloud-consul
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - brianshumate.consul
