- name: Provide elasticsearch.repo to /etc/yum.repos.d/elasticsearch.repo
  template: src=elasticsearch.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo
  when: ENABLE_LOCAL_YUM_REPOS | bool == false

- name: Install elasticsearch
  yum: name={{item}}
  loop:
    - java
    - elasticsearch
