- name: Provide neutron.conf to /etc/neutron/neutron.conf for Compute Nodes
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf
  notify:
    - Restart neutron-openvswitch-agent
  when: inventory_hostname not in groups['cloud-controller'] 

- name: Provide openvswitch_agent.ini to /etc/neutron/plugins/ml2/openvswitch_agent.ini for Compute Nodes
  template: src=openvswitch_agent.ini.j2 dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
  notify:
    - Restart neutron-openvswitch-agent

- name: Enable and Start neutron-openvswitch-agent
  service: name=neutron-openvswitch-agent state=started enabled=yes
