- name: Install Base Package
  yum: name={{item}} state=present update_cache=yes
  loop:
    - bash-completion
    - bash-completion-extras
    - chrony
    - lrzsz
    - net-tools
    - tree
    - tcpdump
    - vim
    - lsof
    - unzip
    - sysstat
    - python2-pip
    - python36-pip
    - bridge-utils
    - fping
    - fio
    - wget
    - strace
    - curl
    - rsync
    - sshpass
    - telnet
    - bridge-utils
    - iproute
    - psmisc
    - atop
    - htop
    - dstat
    - iftop
    - iotop
    - perf
    - ebtables
    - ethtool
    - nc
    - smartmontools
    - ipmitool
    - ipmiutil
    - which
    - pstree
