- name: Set sysctl.conf
  sysctl: name={{ item.name }} value="{{item.value}}" state={{ item.state }} sysctl_set=yes reload=yes ignoreerrors=yes
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '1', state: 'present' }
    #- { name: 'net.ipv4.ip_local_port_range', value: '40000 65000', state: 'present' }
    - { name: 'net.ipv4.tcp_mem', value: '94500000 915000000 927000000', state: 'present' }
    - { name: 'net.core.netdev_max_backlog', value: '262144', state: 'present' }
    - { name: 'net.ipv4.conf.all.arp_filter', value: '1', state: 'present' }
    - { name: 'net.ipv4.conf.default.arp_filter', value: '1', state: 'present' }
    - { name: 'net.ipv4.ip_nonlocal_bind', value: '1', state: 'present' }
    - { name: 'net.ipv4.conf.all.rp_filter', value: '0', state: 'present' }
    - { name: 'net.ipv4.conf.default.rp_filter', value: '0', state: 'present' }
    - { name: 'net.ipv4.tcp_fastopen', value: '3', state: 'present' }
    - { name: 'net.ipv4.tcp_max_orphans', value: '262144', state: 'present' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '262144', state: 'present' }
    - { name: 'net.ipv4.tcp_synack_retries', value: '1', state: 'present' }
    - { name: 'net.ipv4.tcp_syncookies', value: '1', state: 'present' }
    - { name: 'net.ipv4.tcp_tw_reuse', value: '1', state: 'present' }
    #- { name: 'net.ipv4.tcp_tw_recycle', value: '1', state: 'present' }
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: '100000', state: 'present' }
    - { name: 'net.ipv4.tcp_timestamps', value: '0', state: 'present' }
    - { name: 'net.ipv4.tcp_fin_timeout', value: '30', state: 'present' }
    - { name: 'net.ipv4.tcp_keepalive_time', value: '600', state: 'present' }
    - { name: 'net.ipv4.tcp_keepalive_probes', value: '3', state: 'present' }
    - { name: 'net.ipv4.tcp_keepalive_intvl', value: '15', state: 'present' }
    - { name: 'net.core.busy_read', value: '50', state: 'present' }
    - { name: 'net.core.busy_poll', value: '50', state: 'present' }
    - { name: 'vm.swappiness', value: '1', state: 'present' }
    - { name: 'vm.dirty_ratio', value: '40', state: 'present' }
    - { name: 'vm.dirty_background_ratio', value: '10', state: 'present' }
    - { name: 'vm.vfs_cache_pressure', value: '200', state: 'present' }
    - { name: 'kernel.pid_max', value: '4194304', state: 'present' }
    - { name: 'kernel.shmmax', value: '2147483648', state: 'present' }
    - { name: 'kernel.shmall', value: '134217728', state: 'present' }
    - { name: 'kernel.shmmni', value: '4096', state: 'present' }
    - { name: 'kernel.perf_event_max_sample_rate', value: '50000', state: 'present' }
    - { name: 'kernel.sched_min_granularity_ns', value: '10000000', state: 'present' }
    - { name: 'kernel.sched_wakeup_granularity_ns', value: '15000000', state: 'present' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1', state: 'present' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1', state: 'present' }
    - { name: 'net.bridge.bridge-nf-call-arptables', value: '1', state: 'present' }
    - { name: 'vm.max_map_count', value: '655360', state: 'present' }
#    - { name: 'net.netfilter.nf_conntrack_max', value: '41237300', state: 'present' }
#    - { name: 'net.netfilter.nf_conntrack_tcp_timeout_established', value: '180', state: 'present' }
