- name: Provide zabbix.repo to /etc/yum.repos.d/zabbix.repo
  template: src=zabbix.repo dest=/etc/yum.repos.d/zabbix.repo
  when: ENABLE_LOCAL_YUM_REPOS | bool == false

- name: Install Zabbix Server
  yum: name={{item}}
  loop:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-get
