- block:
    - name: Create DATABASE nova_api for nova service
      mysql_db: name=nova_api state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock

    - name: GRANT ALL PRIVILEGES for nova_api
      mysql_user: name={{NOVA_DBUSER}} password='{% if GLOBAL_PASS %}{{GLOBAL_PASS}}{% else %}{{NOVA_DBPASS}}{% endif %}' priv=nova_api.*:ALL host={{item}} state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock append_privs=true
      loop:
        - 'localhost'
        - '%'

    - name: Create DATABASE nova for nova service
      mysql_db: name=nova state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock

    - name: GRANT ALL PRIVILEGES for nova
      mysql_user: name={{NOVA_DBUSER}} password='{% if GLOBAL_PASS %}{{GLOBAL_PASS}}{% else %}{{NOVA_DBPASS}}{% endif %}' priv=nova.*:ALL host={{item}} state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock append_privs=true
      loop:
        - 'localhost'
        - '%'

    - name: Create DATABASE nova_cell0 for nova service
      mysql_db: name=nova_cell0 state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock

    - name: GRANT ALL PRIVILEGES for nova_cell0
      mysql_user: name={{NOVA_DBUSER}} password='{% if GLOBAL_PASS %}{{GLOBAL_PASS}}{% else %}{{NOVA_DBPASS}}{% endif %}' priv=nova_cell0.*:ALL host={{item}} state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock append_privs=true
      loop:
        - 'localhost'
        - '%'

    - name: Create DATABASE placement for nova service
      mysql_db: name=placement state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock

    - name: GRANT ALL PRIVILEGES for nova_api
      mysql_user: name={{PLACEMENT_DBUSER}} password='{% if GLOBAL_PASS %}{{GLOBAL_PASS}}{% else %}{{PLACEMENT_DBPASS}}{% endif %}' priv=placement.*:ALL host={{item}} state=present login_host=localhost login_port={{MYSQL_PORT}} login_unix_socket=/var/lib/mysql/mysql.sock
      loop:
        - 'localhost'
        - '%'
  run_once: yes
  delegate_to: "{{groups['cloud-database'][0]}}"
