- name: Provide influxdb.repo to /etc/yum.repos.d/influxdb.repo
  copy: src=influxdb.repo dest=/etc/yum.repos.d/influxdb.repo
  when: ENABLE_LOCAL_YUM_REPOS | bool == false

- name: Install telegraf
  yum: name={{item}} state=installed
  with_items:
    - telegraf
